services:
  - type: web
    name: xerxex-banking-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://bankbackend-y4qi.onrender.com
    staticSite:
      buildDir: dist
      routes:
        - path: /*
          dest: /index.html
          status: 200
